# Model arguments
model_name_or_path: /maas-vepfs//models/mistral-instruct-7b

# Data training arguments
dataset_mixer:
  /root/code/opensource/SPIN/spin-generated/mistral-7b/iter0_post: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# Trainer arguments
bf16: true
beta: 0.1
do_eval: true
evaluation_strategy: "steps"
eval_steps: 500
gradient_accumulation_steps: 1
gradient_checkpointing: true
hub_model_id: test-7b
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
optim: rmsprop
output_dir: outputs
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1
